name: 협업 이슈 템플릿
description: 협업 시 사용될 이슈 템플릿입니다.

body:
  -type: markdown
  attrubutes:
    value: |
    ### Issue를 생성하는 목적

-type: textarea
id: purpose
attributes:
  label: 목적
  description: Issue 생성 목적 간단히 설명하기 (생략불가) ex) 버그 수정, 기능 추가, 기능 개선 등
  validations:
    required: true

-type: markdown
attributes:
  value: |
  ### 문제 설명

-type: textarea
id: description
attributes:
  label: 설명
  description: 문제에 대해 자세하기 설명하기 (생략가능)
  
